version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: orders
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - dev

networks:
  dev: